### ISSUE TITLE
TypeError: cannot instantiate ctype 'EVP_MD_CTX' of unknown size

### ISSUE THREAD

**Issue by lechup** [kshcherban/acme-nginx#15]
```
sudo acme-nginx -d xxx
Mar 16 10:04:21 Can not open key /etc/ssl/private/letsencrypt-account.key, generating new
Mar 16 10:04:21 Can not open key /etc/ssl/private/xxx.key, generating new
Mar 16 10:04:21 Trying to register account key
Traceback (most recent call last):
  File "/usr/local/bin/acme-nginx", line 9, in <module>
    load_entry_point('acme-nginx==0.0.5', 'console_scripts', 'acme-nginx')()
  File "/usr/local/lib/python2.7/dist-packages/acme_nginx/client.py", line 265, in main
    private_key)
  File "/usr/local/lib/python2.7/dist-packages/acme_nginx/client.py", line 166, in send_signed_request
    signature = sign_message(key, "{0}.{1}".format(protected64, payload64))
  File "/usr/local/lib/python2.7/dist-packages/acme_nginx/client.py", line 132, in sign_message
    return OpenSSL.crypto.sign(pk, message.encode('utf8'), 'sha256')
  File "/usr/lib/python2.7/dist-packages/OpenSSL/crypto.py", line 2403, in sign
    md_ctx = _ffi.new("EVP_MD_CTX*")
TypeError: cannot instantiate ctype 'EVP_MD_CTX' of unknown size
```

Downgrading cryptography to 1.4 `sudo pip install cryptography==1.4` seems to fix the problem...

PS: I've found similar issue here: https://github.com/burnash/gspread/issues/407

**Comment by kshcherban** [comment]
Hmm, cryptography is really not needed for this script but may have already been installed on your system. One the one hand adding it to dependencies is incorrect, on the other it will resolve your issue.
I would prefer to update readme then.

**Comment by lechup** [comment]
pyOpenSSL needs it: https://pypi.python.org/pypi/pyOpenSSL , maybe I should use different version of pyOpenSSL?

**Comment by kshcherban** [comment]
I don't have it installed in my system, only pycrypto and script works fine. Probably because of outdated openssl. Anyway this script shouldn't manage openssl deps. Closing.
```
pip list | grep crypto
pycrypto (2.6)
```

**Comment by shaungrady** [comment]
If it's of an consequence, I encountered this issue today. Here's my install log:

```
Installed /usr/local/lib/python2.7/dist-packages/acme_nginx-0.0.5-py2.7.egg
Processing dependencies for acme-nginx==0.0.5
Searching for pycrypto==2.6.1
Best match: pycrypto 2.6.1
Adding pycrypto 2.6.1 to easy-install.pth file

Using /usr/lib/python2.7/dist-packages
Searching for pyOpenSSL==16.0.0
Best match: pyOpenSSL 16.0.0
Adding pyOpenSSL 16.0.0 to easy-install.pth file

Using /usr/lib/python2.7/dist-packages
Searching for six==1.10.0
Best match: six 1.10.0
Adding six 1.10.0 to easy-install.pth file

Using /usr/lib/python2.7/dist-packages
Searching for cryptography==1.7.1
Best match: cryptography 1.7.1
Adding cryptography 1.7.1 to easy-install.pth file

Using /usr/lib/python2.7/dist-packages
Finished processing dependencies for acme-nginx==0.0.5
```

Took some wrestling in the form of making sure I had all the necessary packages installed, but I downgraded cryptography to 1.4 and it did indeed fix it.
