### ISSUE TITLE
pkg_resources.DistributionNotFound: The 'cryptography>=2.1.4' distribution was not found and is required by pyOpenSSL

### ISSUE THREAD

**Issue by lakano** [kshcherban/acme-nginx#28]
Hi !
I'm using your script since many time now, and it's worked like a charm until today.
All my SSL cert have expired today, I've checked the logs of acme-nginx script and it's because one domain haven't been renewed. So, I've removed it, but the script doesn't work anymore:

```
Traceback (most recent call last):
  File "/usr/local/bin/acme-nginx", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3019, in <module>
    @_call_aside
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3003, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3032, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 657, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 670, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 849, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'cryptography>=2.1.4' distribution was not found and is required by pyOpenSSL


````

It's may be because of my last server upgrade since the last call of acme-nginx.
The problem seems to be about cryptography (PyOpenSSL ?).
I've updated your script (I was previously on 0.0.7 before) but this can't install it correctly:

```
# LANG=C python setup.py install
running install
running bdist_egg
running egg_info
writing requirements to acme_nginx.egg-info/requires.txt
writing acme_nginx.egg-info/PKG-INFO
writing top-level names to acme_nginx.egg-info/top_level.txt
writing dependency_links to acme_nginx.egg-info/dependency_links.txt
writing entry points to acme_nginx.egg-info/entry_points.txt
reading manifest file 'acme_nginx.egg-info/SOURCES.txt'
writing manifest file 'acme_nginx.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/acme_nginx
copying build/lib.linux-x86_64-2.7/acme_nginx/__init__.py -> build/bdist.linux-x86_64/egg/acme_nginx
copying build/lib.linux-x86_64-2.7/acme_nginx/client.py -> build/bdist.linux-x86_64/egg/acme_nginx
byte-compiling build/bdist.linux-x86_64/egg/acme_nginx/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/acme_nginx/client.py to client.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying acme_nginx.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying acme_nginx.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying acme_nginx.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying acme_nginx.egg-info/entry_points.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying acme_nginx.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying acme_nginx.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating 'dist/acme_nginx-0.0.8-py2.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing acme_nginx-0.0.8-py2.7.egg
Removing /usr/local/lib/python2.7/dist-packages/acme_nginx-0.0.8-py2.7.egg
Copying acme_nginx-0.0.8-py2.7.egg to /usr/local/lib/python2.7/dist-packages
acme-nginx 0.0.8 is already the active version in easy-install.pth
Installing acme-nginx script to /usr/local/bin

Installed /usr/local/lib/python2.7/dist-packages/acme_nginx-0.0.8-py2.7.egg
Processing dependencies for acme-nginx==0.0.8
Searching for cryptography>=2.1.4
Reading https://pypi.python.org/simple/cryptography/
Downloading https://pypi.python.org/packages/78/c5/7188f15a92413096c93053d5304718e1f6ba88b818357d05d19250ebff85/cryptography-2.1.4.tar.gz#md5=9f39d4d8f2b05f295fa0ff52475ec4f2
Best match: cryptography 2.1.4
Processing cryptography-2.1.4.tar.gz
Writing /tmp/easy_install-Y9yFU0/cryptography-2.1.4/setup.cfg
Running cryptography-2.1.4/setup.py -q bdist_egg --dist-dir /tmp/easy_install-Y9yFU0/cryptography-2.1.4/egg-dist-tmp-uKntfK
no previously-included directories found matching 'docs/_build'
warning: no previously-included files matching '*' found under directory 'vectors'
build/temp.linux-x86_64-2.7/_openssl.c:12:24: fatal error: pyconfig.h: No such file or directory
 #  include <pyconfig.h>
                        ^
compilation terminated.
error: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
root@XXXX:/srv/www/acme-nginx# uname -a
Linux XXXX 4.9.0-0.bpo.4-amd64 #1 SMP Debian 4.9.51-1~bpo8+1 (2017-10-17) x86_64 GNU/Linux
```

Any help will be really appreciated !
Best regards,

**Comment by lakano** [comment]
I've solved my problem by installing theses libraries:
`apt-get install build-essential libssl-dev libffi-dev python-dev`

**Comment by shweta647** [comment]
In windows:
Open Command prompt and install following:
pip install cryptography
pip install lxml
pip install networkx
pip install future
