### ISSUE TITLE
configure: error: no acceptable C compiler found in $PATH

### ISSUE THREAD

**Issue by bizlevel** [kshcherban/acme-nginx#42]
https://github.com/kshcherban/acme-nginx#centosredhatfedora-way
Not enough dependency 

```
[root@bizlevel acme-nginx]# yum install -y pyOpenSSL python-crypto python-setuptools
Loaded plugins: fastestmirror
Setting up Install Process
Determining fastest mirrors
epel/metalink                                                                                                                                              |  30 kB     00:00
 * base: centos.colocall.net
 * epel: mirrors.colocall.net
 * extras: centos.colocall.net
 * remi-php56: remi.schlundtech.de
 * remi-safe: remi.schlundtech.de
 * updates: centos.colocall.net
base                                                                                                                                                       | 3.7 kB     00:00
epel                                                                                                                                                       | 3.2 kB     00:00
epel/primary                                                                                                                                               | 3.2 MB     00:00
epel                                                                                                                                                                  12516/12516
extras                                                                                                                                                     | 3.4 kB     00:00
nginx                                                                                                                                                      | 2.9 kB     00:00
remi-php56                                                                                                                                                 | 2.9 kB     00:00
remi-php56/primary_db                                                                                                                                      | 230 kB     00:00
remi-safe                                                                                                                                                  | 2.9 kB     00:00
remi-safe/primary_db                                                                                                                                       | 1.1 MB     00:00
updates                                                                                                                                                    | 3.4 kB     00:00
updates/primary_db                                                                                                                                         | 1.9 MB     00:00
Package python-setuptools-0.6.10-4.el6_9.noarch already installed and latest version
Resolving Dependencies
--> Running transaction check
---> Package pyOpenSSL.x86_64 0:0.13.1-2.el6 will be installed
---> Package python-crypto.x86_64 0:2.0.1-22.el6 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

==================================================================================================================================================================================
 Package                                        Arch                                    Version                                       Repository                             Size
==================================================================================================================================================================================
Installing:
 pyOpenSSL                                      x86_64                                  0.13.1-2.el6                                  base                                  263 k
 python-crypto                                  x86_64                                  2.0.1-22.el6                                  base                                  159 k

Transaction Summary
==================================================================================================================================================================================
Install       2 Package(s)

Total download size: 422 k
Installed size: 1.8 M
Downloading Packages:
(1/2): pyOpenSSL-0.13.1-2.el6.x86_64.rpm                                                                                                                   | 263 kB     00:00
(2/2): python-crypto-2.0.1-22.el6.x86_64.rpm                                                                                                               | 159 kB     00:00
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total                                                                                                                                             1.2 MB/s | 422 kB     00:00
Running rpm_check_debug
Running Transaction Test
Transaction Test Succeeded
Running Transaction
  Installing : python-crypto-2.0.1-22.el6.x86_64                                                                                                                              1/2
  Installing : pyOpenSSL-0.13.1-2.el6.x86_64                                                                                                                                  2/2
  Verifying  : pyOpenSSL-0.13.1-2.el6.x86_64                                                                                                                                  1/2
  Verifying  : python-crypto-2.0.1-22.el6.x86_64                                                                                                                              2/2

Installed:
  pyOpenSSL.x86_64 0:0.13.1-2.el6                                                       python-crypto.x86_64 0:2.0.1-22.el6

Complete!

[root@bizlevel acme-nginx]# python setup.py install
/usr/lib64/python2.6/distutils/dist.py:266: UserWarning: Unknown distribution option: 'long_description_content_type'
  warnings.warn(msg)
running install
running bdist_egg
running egg_info
writing requirements to acme_nginx.egg-info/requires.txt
writing acme_nginx.egg-info/PKG-INFO
writing top-level names to acme_nginx.egg-info/top_level.txt
writing dependency_links to acme_nginx.egg-info/dependency_links.txt
writing entry points to acme_nginx.egg-info/entry_points.txt
reading manifest file 'acme_nginx.egg-info/SOURCES.txt'
writing manifest file 'acme_nginx.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/acme_nginx
copying build/lib/acme_nginx/AcmeV1.py -> build/bdist.linux-x86_64/egg/acme_nginx
copying build/lib/acme_nginx/Acme.py -> build/bdist.linux-x86_64/egg/acme_nginx
copying build/lib/acme_nginx/AcmeV2.py -> build/bdist.linux-x86_64/egg/acme_nginx
copying build/lib/acme_nginx/__init__.py -> build/bdist.linux-x86_64/egg/acme_nginx
copying build/lib/acme_nginx/client.py -> build/bdist.linux-x86_64/egg/acme_nginx
copying build/lib/acme_nginx/DigitalOcean.py -> build/bdist.linux-x86_64/egg/acme_nginx
byte-compiling build/bdist.linux-x86_64/egg/acme_nginx/AcmeV1.py to AcmeV1.pyc
byte-compiling build/bdist.linux-x86_64/egg/acme_nginx/Acme.py to Acme.pyc
byte-compiling build/bdist.linux-x86_64/egg/acme_nginx/AcmeV2.py to AcmeV2.pyc
byte-compiling build/bdist.linux-x86_64/egg/acme_nginx/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/acme_nginx/client.py to client.pyc
byte-compiling build/bdist.linux-x86_64/egg/acme_nginx/DigitalOcean.py to DigitalOcean.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying acme_nginx.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying acme_nginx.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying acme_nginx.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying acme_nginx.egg-info/entry_points.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying acme_nginx.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying acme_nginx.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating 'dist/acme_nginx-0.1.3-py2.6.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing acme_nginx-0.1.3-py2.6.egg
removing '/usr/lib/python2.6/site-packages/acme_nginx-0.1.3-py2.6.egg' (and everything under it)
creating /usr/lib/python2.6/site-packages/acme_nginx-0.1.3-py2.6.egg
Extracting acme_nginx-0.1.3-py2.6.egg to /usr/lib/python2.6/site-packages
acme-nginx 0.1.3 is already the active version in easy-install.pth
Installing acme-nginx script to /usr/bin

Installed /usr/lib/python2.6/site-packages/acme_nginx-0.1.3-py2.6.egg
Processing dependencies for acme-nginx==0.1.3
Searching for pycrypto>=2.6
Reading https://pypi.python.org/simple/pycrypto/
Best match: pycrypto 2.6.1
Downloading https://files.pythonhosted.org/packages/60/db/645aa9af249f059cc3a368b118de33889219e0362141e75d4eaf6f80f163/pycrypto-2.6.1.tar.gz#sha256=f2ce1e989b272cfcb677616763e0a2e7ec659effa67a88aa92b3a65528f60a3c
Processing pycrypto-2.6.1.tar.gz
Running pycrypto-2.6.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-ddAFps/pycrypto-2.6.1/egg-dist-tmp-cWTj0X
configure: error: in `/tmp/easy_install-ddAFps/pycrypto-2.6.1':
configure: error: no acceptable C compiler found in $PATH
See `config.log' for more details
Traceback (most recent call last):
  File "setup.py", line 29, in <module>
    'acme-nginx = acme_nginx.client:main',
  File "/usr/lib64/python2.6/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/usr/lib64/python2.6/distutils/dist.py", line 975, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python2.6/distutils/dist.py", line 995, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.6/site-packages/setuptools/command/install.py", line 73, in run
    self.do_egg_install()
  File "/usr/lib/python2.6/site-packages/setuptools/command/install.py", line 101, in do_egg_install
    cmd.run()
  File "/usr/lib/python2.6/site-packages/setuptools/command/easy_install.py", line 236, in run
    self.easy_install(spec, not self.no_deps)
  File "/usr/lib/python2.6/site-packages/setuptools/command/easy_install.py", line 452, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/usr/lib/python2.6/site-packages/setuptools/command/easy_install.py", line 504, in install_item
    self.process_distribution(spec, dist, deps)
  File "/usr/lib/python2.6/site-packages/setuptools/command/easy_install.py", line 545, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 538, in resolve
    dist = best[req.key] = env.best_match(req, self, installer)
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 780, in best_match
    return self.obtain(req, installer) # try and download/install
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 792, in obtain
    return installer(requirement)
  File "/usr/lib/python2.6/site-packages/setuptools/command/easy_install.py", line 472, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/usr/lib/python2.6/site-packages/setuptools/command/easy_install.py", line 502, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/usr/lib/python2.6/site-packages/setuptools/command/easy_install.py", line 681, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/usr/lib/python2.6/site-packages/setuptools/command/easy_install.py", line 958, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/usr/lib/python2.6/site-packages/setuptools/command/easy_install.py", line 947, in run_setup
    run_setup(setup_script, args)
  File "/usr/lib/python2.6/site-packages/setuptools/sandbox.py", line 29, in run_setup
    lambda: execfile(
  File "/usr/lib/python2.6/site-packages/setuptools/sandbox.py", line 70, in run
    return func()
  File "/usr/lib/python2.6/site-packages/setuptools/sandbox.py", line 31, in <lambda>
    {'__file__':setup_script, '__name__':'__main__'}
  File "setup.py", line 456, in <module>

  File "/usr/lib64/python2.6/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/usr/lib64/python2.6/distutils/dist.py", line 975, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python2.6/distutils/dist.py", line 995, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.6/site-packages/setuptools/command/bdist_egg.py", line 174, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/usr/lib/python2.6/site-packages/setuptools/command/bdist_egg.py", line 161, in call_command
    self.run_command(cmdname)
  File "/usr/lib64/python2.6/distutils/cmd.py", line 333, in run_command
    self.distribution.run_command(command)
  File "/usr/lib64/python2.6/distutils/dist.py", line 995, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.6/site-packages/setuptools/command/install_lib.py", line 20, in run
    self.build()
  File "/usr/lib64/python2.6/distutils/command/install_lib.py", line 119, in build
    self.run_command('build_ext')
  File "/usr/lib64/python2.6/distutils/cmd.py", line 333, in run_command
    self.distribution.run_command(command)
  File "/usr/lib64/python2.6/distutils/dist.py", line 995, in run_command
    cmd_obj.run()
  File "setup.py", line 251, in run

  File "/usr/lib64/python2.6/distutils/cmd.py", line 333, in run_command
    self.distribution.run_command(command)
  File "/usr/lib64/python2.6/distutils/dist.py", line 995, in run_command
    cmd_obj.run()
  File "setup.py", line 278, in run

RuntimeError: autoconf error
[root@bizlevel acme-nginx]#

```

**Comment by kshcherban** [comment]
You are missing gcc to compile python dependencies.

**Comment by bizlevel** [comment]
Hm, issues was closed, but readme ( https://github.com/kshcherban/acme-nginx#centosredhatfedora-way ) not changes.

**Comment by kshcherban** [comment]
It was changed, i added line `sudo yum groupinstall -y "Development tools"`
