### ISSUE TITLE
Unable to get local issuer certificate 

### ISSUE THREAD

**Issue by androos** [kshcherban/acme-nginx#55]
I updated from 1.2 to 2.1 but now I get only this error:
```
INFO - trying to create account key /etc/ssl/private/letsencrypt-account.key
Traceback (most recent call last):
  File "urllib/request.py", line 1317, in do_open
  File "http/client.py", line 1244, in request
  File "http/client.py", line 1290, in _send_request
  File "http/client.py", line 1239, in endheaders
  File "http/client.py", line 1026, in _send_output
  File "http/client.py", line 966, in send
  File "http/client.py", line 1414, in connect
  File "ssl.py", line 423, in wrap_socket
  File "ssl.py", line 870, in _create
  File "ssl.py", line 1139, in do_handshake
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1076)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "acme-runner.py", line 11, in <module>
  File "acme_nginx/client.py", line 112, in main
  File "acme_nginx/AcmeV2.py", line 186, in get_certificate
  File "acme_nginx/AcmeV2.py", line 31, in register_account
  File "urllib/request.py", line 222, in urlopen
  File "urllib/request.py", line 525, in open
  File "urllib/request.py", line 543, in _open
  File "urllib/request.py", line 503, in _call_chain
  File "urllib/request.py", line 1360, in https_open
  File "urllib/request.py", line 1319, in do_open
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1076)>
[35828] Failed to execute script acme-runner
```
This is how I use it.
`acme-nginx -k /etc/ssl/private/letsencrypt-account.key -d www.domain -d domain -o "/etc/ssl/certs/www.domain.cert" --domain-private-key "/etc/ssl/private/domain.key"`

**Comment by androos** [comment]
Well it works with the bin create with pip install.

**Comment by kshcherban** [comment]
Usually this happens because of missing CA certificates system package.

**Comment by androos** [comment]
app-misc/ca-certificates is installed.
