### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by ehcpdeveloper** [kshcherban/acme-nginx#58]
```
dom="xxxx.net"
# acme-nginx --domain-private-key /etc/ssl/private/letsencrypt-$dom.key -o /etc/ssl/private/letsencrypt-xxxx.net.pem -d xxxx.net -d '*.xxxx.net'
2022-04-14 02:00:33,704 - INFO - trying to create account key /etc/ssl/private/letsencrypt-account.key
2022-04-14 02:00:38,819 - INFO - trying to register acmev2 account
2022-04-14 02:00:39,028 - INFO - already registered
2022-04-14 02:00:39,028 - INFO - trying to create domain key
2022-04-14 02:00:39,028 - INFO - acmev2 http challenge
2022-04-14 02:00:39,028 - INFO - preparing new order
2022-04-14 02:00:39,295 - INFO - order created
2022-04-14 02:00:39,531 - INFO - verifying domain xxxx.net
Traceback (most recent call last):
  File "/usr/local/bin/acme-nginx", line 11, in <module>
    load_entry_point('acme-nginx==0.3.0', 'console_scripts', 'acme-nginx')()
  File "/usr/local/lib/python3.8/dist-packages/acme_nginx-0.3.0-py3.8.egg/acme_nginx/client.py", line 131, in main
  File "/usr/local/lib/python3.8/dist-packages/acme_nginx-0.3.0-py3.8.egg/acme_nginx/AcmeV2.py", line 221, in get_certificate
  File "/usr/local/lib/python3.8/dist-packages/acme_nginx-0.3.0-py3.8.egg/acme_nginx/AcmeV2.py", line 113, in solve_http_challenge
TypeError: 'NoneType' object is not subscriptable
```

Not usable in wildcard domains.

**Comment by kshcherban** [comment]
Wildcard certificates can't be used with http challenge. Please check LE FAQat https://letsencrypt.org/docs/faq/#does-let-s-encrypt-issue-wildcard-certificates

**Comment by ehcpdeveloper** [comment]
Then, a relevant error message could be displayed, not python programming error. 
Anyway, thanks for info.
