### ISSUE TITLE
error

### ISSUE THREAD

**Issue by coltguo** [kshcherban/acme-nginx#62]
![image](https://user-images.githubusercontent.com/26832106/192224775-29fe2ff6-444a-4399-b058-3d3b9f0ee9c5.png)

**Comment by coltguo** [comment]
Traceback (most recent call last):
  File "/usr/local/bin/acme-nginx", line 33, in <module>
    sys.exit(load_entry_point('acme-nginx==0.3.2', 'console_scripts', 'acme-nginx')())
  File "/usr/local/bin/acme-nginx", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/python/lib/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/python/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/python/lib/python3.9/site-packages/acme_nginx-0.3.2-py3.9.egg/acme_nginx/client.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/python/lib/python3.9/site-packages/acme_nginx-0.3.2-py3.9.egg/acme_nginx/AcmeV1.py", line 11, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/python/lib/python3.9/site-packages/acme_nginx-0.3.2-py3.9.egg/acme_nginx/Acme.py", line 2, in <module>
  File "/usr/python/lib/python3.9/site-packages/pyOpenSSL-20.0.1-py3.9.egg/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/usr/python/lib/python3.9/site-packages/pyOpenSSL-20.0.1-py3.9.egg/OpenSSL/crypto.py", line 1556, in <module>
    class X509StoreFlags(object):
  File "/usr/python/lib/python3.9/site-packages/pyOpenSSL-20.0.1-py3.9.egg/OpenSSL/crypto.py", line 1577, in X509StoreFlags
    CB_ISSUER_CHECK = _lib.X509_V_FLAG_CB_ISSUER_CHECK
AttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'
root@vp:/home/acme-nginx# pip3 install lib
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
ERROR: Exception:
Traceback (most recent call last):
  File "/usr/python/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 228, in _main
    status = self.run(options, args)
  File "/usr/python/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 182, in wrapper
    return func(self, options, args)
  File "/usr/python/lib/python3.9/site-packages/pip/_internal/commands/install.py", line 272, in run
    session = self.get_default_session(options)
  File "/usr/python/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 80, in get_default_session
    self._session = self.enter_context(self._build_session(options))
  File "/usr/python/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 90, in _build_session
    session = PipSession(
  File "/usr/python/lib/python3.9/site-packages/pip/_internal/network/session.py", line 249, in __init__
    self.headers["User-Agent"] = user_agent()
  File "/usr/python/lib/python3.9/site-packages/pip/_internal/network/session.py", line 132, in user_agent
    zip(["name", "version", "id"], distro.linux_distribution()),
  File "/usr/python/lib/python3.9/site-packages/pip/_vendor/distro.py", line 125, in linux_distribution
    return _distro.linux_distribution(full_distribution_name)
  File "/usr/python/lib/python3.9/site-packages/pip/_vendor/distro.py", line 681, in linux_distribution
    self.version(),
  File "/usr/python/lib/python3.9/site-packages/pip/_vendor/distro.py", line 741, in version
    self.lsb_release_attr('release'),
  File "/usr/python/lib/python3.9/site-packages/pip/_vendor/distro.py", line 903, in lsb_release_attr
    return self._lsb_release_info.get(attribute, '')
  File "/usr/python/lib/python3.9/site-packages/pip/_vendor/distro.py", line 556, in __get__
    ret = obj.__dict__[self._fname] = self._f(obj)
  File "/usr/python/lib/python3.9/site-packages/pip/_vendor/distro.py", line 1014, in _lsb_release_info
    stdout = subprocess.check_output(cmd, stderr=devnull)
  File "/usr/python/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/python/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '('lsb_release', '-a')' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/usr/bin/pip3", line 11, in <module>
    sys.exit(main())
  File "/usr/python/lib/python3.9/site-packages/pip/__init__.py", line 18, in main
    return _wrapper(args)
  File "/usr/python/lib/python3.9/site-packages/pip/_internal/utils/entrypoints.py", line 31, in _wrapper
    return main(args)
  File "/usr/python/lib/python3.9/site-packages/pip/_internal/cli/main.py", line 75, in main
    return command.main(cmd_args)
  File "/usr/python/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 121, in main
    return self._main(args)
  File "/usr/python/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 265, in _main
    self.handle_pip_version_check(options)
  File "/usr/python/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 149, in handle_pip_version_check
    session = self._build_session(
  File "/usr/python/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 90, in _build_session
    session = PipSession(
  File "/usr/python/lib/python3.9/site-packages/pip/_internal/network/session.py", line 249, in __init__
    self.headers["User-Agent"] = user_agent()
  File "/usr/python/lib/python3.9/site-packages/pip/_internal/network/session.py", line 132, in user_agent
    zip(["name", "version", "id"], distro.linux_distribution()),
  File "/usr/python/lib/python3.9/site-packages/pip/_vendor/distro.py", line 125, in linux_distribution
    return _distro.linux_distribution(full_distribution_name)
  File "/usr/python/lib/python3.9/site-packages/pip/_vendor/distro.py", line 681, in linux_distribution
    self.version(),
  File "/usr/python/lib/python3.9/site-packages/pip/_vendor/distro.py", line 741, in version
    self.lsb_release_attr('release'),
  File "/usr/python/lib/python3.9/site-packages/pip/_vendor/distro.py", line 903, in lsb_release_attr
    return self._lsb_release_info.get(attribute, '')
  File "/usr/python/lib/python3.9/site-packages/pip/_vendor/distro.py", line 556, in __get__
    ret = obj.__dict__[self._fname] = self._f(obj)
  File "/usr/python/lib/python3.9/site-packages/pip/_vendor/distro.py", line 1014, in _lsb_release_info
    stdout = subprocess.check_output(cmd, stderr=devnull)
  File "/usr/python/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/python/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '('lsb_release', '-a')' returned non-zero exit status 1.
root@vp:/home/acme-nginx# pip install lib
ERROR: Exception:
Traceback (most recent call last):
  File "/usr/python/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 228, in _main
    status = self.run(options, args)
  File "/usr/python/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 182, in wrapper
    return func(self, options, args)
  File "/usr/python/lib/python3.9/site-packages/pip/_internal/commands/install.py", line 272, in run
    session = self.get_default_session(options)
  File "/usr/python/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 80, in get_default_session
    self._session = self.enter_context(self._build_session(options))
  File "/usr/python/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 90, in _build_session
    session = PipSession(
  File "/usr/python/lib/python3.9/site-packages/pip/_internal/network/session.py", line 249, in __init__
    self.headers["User-Agent"] = user_agent()
  File "/usr/python/lib/python3.9/site-packages/pip/_internal/network/session.py", line 132, in user_agent
    zip(["name", "version", "id"], distro.linux_distribution()),
  File "/usr/python/lib/python3.9/site-packages/pip/_vendor/distro.py", line 125, in linux_distribution
    return _distro.linux_distribution(full_distribution_name)
  File "/usr/python/lib/python3.9/site-packages/pip/_vendor/distro.py", line 681, in linux_distribution
    self.version(),
  File "/usr/python/lib/python3.9/site-packages/pip/_vendor/distro.py", line 741, in version
    self.lsb_release_attr('release'),
  File "/usr/python/lib/python3.9/site-packages/pip/_vendor/distro.py", line 903, in lsb_release_attr
    return self._lsb_release_info.get(attribute, '')
  File "/usr/python/lib/python3.9/site-packages/pip/_vendor/distro.py", line 556, in __get__
    ret = obj.__dict__[self._fname] = self._f(obj)
  File "/usr/python/lib/python3.9/site-packages/pip/_vendor/distro.py", line 1014, in _lsb_release_info
    stdout = subprocess.check_output(cmd, stderr=devnull)
  File "/usr/python/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/python/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '('lsb_release', '-a')' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/usr/bin/pip", line 8, in <module>
    sys.exit(main())
  File "/usr/python/lib/python3.9/site-packages/pip/_internal/cli/main.py", line 75, in main
    return command.main(cmd_args)
  File "/usr/python/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 121, in main
    return self._main(args)
  File "/usr/python/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 265, in _main
    self.handle_pip_version_check(options)
  File "/usr/python/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 149, in handle_pip_version_check
    session = self._build_session(
  File "/usr/python/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 90, in _build_session
    session = PipSession(
  File "/usr/python/lib/python3.9/site-packages/pip/_internal/network/session.py", line 249, in __init__
    self.headers["User-Agent"] = user_agent()
  File "/usr/python/lib/python3.9/site-packages/pip/_internal/network/session.py", line 132, in user_agent
    zip(["name", "version", "id"], distro.linux_distribution()),
  File "/usr/python/lib/python3.9/site-packages/pip/_vendor/distro.py", line 125, in linux_distribution
    return _distro.linux_distribution(full_distribution_name)
  File "/usr/python/lib/python3.9/site-packages/pip/_vendor/distro.py", line 681, in linux_distribution
    self.version(),
  File "/usr/python/lib/python3.9/site-packages/pip/_vendor/distro.py", line 741, in version
    self.lsb_release_attr('release'),
  File "/usr/python/lib/python3.9/site-packages/pip/_vendor/distro.py", line 903, in lsb_release_attr
    return self._lsb_release_info.get(attribute, '')
  File "/usr/python/lib/python3.9/site-packages/pip/_vendor/distro.py", line 556, in __get__
    ret = obj.__dict__[self._fname] = self._f(obj)
  File "/usr/python/lib/python3.9/site-packages/pip/_vendor/distro.py", line 1014, in _lsb_release_info
    stdout = subprocess.check_output(cmd, stderr=devnull)
  File "/usr/python/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/python/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '('lsb_release', '-a')' returned non-zero exit status 1.

**Comment by coltguo** [comment]
Traceback (most recent call last):
  File "/usr/local/bin/acme-nginx", line 33, in <module>
    sys.exit(load_entry_point('acme-nginx==0.3.2', 'console_scripts', 'acme-nginx')())
  File "/usr/local/bin/acme-nginx", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/python/lib/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/python/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/python/lib/python3.9/site-packages/acme_nginx-0.3.2-py3.9.egg/acme_nginx/client.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/python/lib/python3.9/site-packages/acme_nginx-0.3.2-py3.9.egg/acme_nginx/AcmeV1.py", line 11, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/python/lib/python3.9/site-packages/acme_nginx-0.3.2-py3.9.egg/acme_nginx/Acme.py", line 2, in <module>
  File "/usr/python/lib/python3.9/site-packages/pyOpenSSL-20.0.1-py3.9.egg/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/usr/python/lib/python3.9/site-packages/pyOpenSSL-20.0.1-py3.9.egg/OpenSSL/crypto.py", line 1556, in <module>
    class X509StoreFlags(object):
  File "/usr/python/lib/python3.9/site-packages/pyOpenSSL-20.0.1-py3.9.egg/OpenSSL/crypto.py", line 1577, in X509StoreFlags
    CB_ISSUER_CHECK = _lib.X509_V_FLAG_CB_ISSUER_CHECK
AttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'

**Comment by coltguo** [comment]
Has been resolved，thank you

**Comment by jtc42** [comment]
How did you resolve this?
