### ISSUE TITLE
Error while downloading certificate from Staging Environment

### ISSUE THREAD

**Issue by silmaril42** [kshcherban/acme-nginx#66]
acme-nginx is running fine on my Debian 11 system. Renewing certificates works perfectly.

Only when using the `--staging` flag, it fails after the certificate has been signed successfully.

This is what I see in the log:
```
2024-01-22 07:06:44,153 - INFO - running nginx -s reload
2024-01-22 07:06:44,284 - INFO - signing certificate
2024-01-22 07:06:46,489 - INFO - certificate signed!
2024-01-22 07:06:46,489 - INFO - downloading certificate
Traceback (most recent call last):
  File "/usr/local/bin/acme-nginx", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/acme_nginx/client.py", line 131, in main
    acme.get_certificate()
  File "/usr/local/lib/python3.9/dist-packages/acme_nginx/AcmeV2.py", line 225, in get_certificate
    self.solve_http_challenge(directory)
  File "/usr/local/lib/python3.9/dist-packages/acme_nginx/AcmeV2.py", line 144, in solve_http_challenge
    self._sign_certificate(order, directory)
  File "/usr/local/lib/python3.9/dist-packages/acme_nginx/AcmeV2.py", line 78, in _sign_certificate
    certificate_url = json.loads(result)["certificate"]
KeyError: 'certificate'
```

I am using a call of this format:
```bash
/usr/local/bin/acme-nginx --staging --renew-days 3 -d MYDOMAIN \
  --output /etc/ssl/test/letsencrypt_MYDOMAIN.pem \ 
  --domain-private-key /etc/ssl/test/letsencrypt_MYDOMAIN.key
```
The domain private key file is generated successfully in the given path, but no `*.pem` file is written.

I hope this is the latest acme-nginx version?
```
# /usr/local/bin/acme-nginx --version
acme-nginx 0.3.3
```

Is this a bug in the script or am I doing something wrong on my end?

**Comment by kshcherban** [comment]
Hello,
Thanks for reporting. I guess it's a change in staging API. Will take a look.

**Comment by kshcherban** [comment]
I found that staging finalize reply doesn't contain `certificate` field. Trying to find a workaround.
